version: '3.3'

services:
  users:
    build:
      context: services/users
      dockerfile: Dockerfile
      target: prod
    tty: true
    working_dir: /home/node/app
    volumes:
      - ./services/users:/home/node/app
      - ./services/users/node_modules
    ports:
      - 3001:3000
      - 9291:9229

  mongo:
    build:
      context: mongo
      dockerfile: Dockerfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
    - ./mongo/init:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  rabbitmq:
    image: rabbitmq:3.8.14
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root